name: 'Unique Name Generator'
description: 'Create a unique name'
branding:
  icon: 'align-center'
  color: 'green'
inputs:
  prefix:
    description: 'A fixed prefix to use at the head of the name'
    required: false
  suffix:
    description: 'A fixed suffix to use at the tail of the name'
    required: false 
  separator:
    description: 'What separator to use'
    required: true
    default: '-'
outputs:
  name:
    description: 'The unique name'
runs:
  using: 'node16'
  main: 'dist/index.js'